buildscript {
    ext.kotlin_version = '2.4.20'
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }

    dependencies {
        classpath libs.gradle
        classpath libs.kotlin.gradle.plugin
        classpath libs.python.gradle
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'org.jetbrains.kotlin' &&
                    (details.requested.name == 'kotlin-stdlib-jdk7' || details.requested.name == 'kotlin-stdlib-jdk8')) {
                    details.useVersion '2.4.20'
                }
            }
        }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    afterEvaluate { project ->
        if (project.configurations.findByName("testImplementation") != null) {
            project.dependencies {
                testImplementation 'junit:junit:4.13.2'
                testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
            }
        }
        if (project.hasProperty('android')) {
            project.android {
                // Enforce SDK 37 for all plugins
                compileSdkVersion 37
                //Enforce Ndk 28
                ndkVersion "28.2.13676358"

                defaultConfig {
                    minSdkVersion 24
                }

                buildFeatures {
                    buildConfig true
                }

                // Fallback namespace injection for legacy packages
                if (namespace == null) {
                    namespace project.group ?: "com.example.${project.name.replace('-', '_')}"
                }
                
                // Enforce Java 17 compiler targets
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }
            }
        }
        
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            kotlinOptions {
                jvmTarget = '17'
            }
        }
    }

    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}